---
title: "Covid-19 vaccination risk"
author: "Lars Kroll, Edgar Steiger"
date: "16 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(tidyverse)
library(kableExtra)
```

```{r altersgruppen}
dosen <- 1.77947e6
aktuelle_inzidenz <- 83.7

paramdata <- tibble(Impfdosen=round(c(dosen, dosen/3, dosen/3, dosen/3)),
                    Altersgruppe=c("ohne Differenzierung", "0-59", "60-79", "80+"),
                    "Todesrate COVID-19"=c(73656/2581329, 2523/1930221,19936/396629,51197/254479),
                    "angenommenes Thrombose-Risiko"=7/1.6e6,
                    "7-Tage-Fallrate" = aktuelle_inzidenz/100000)

resultdata <- paramdata %>%
  mutate("mgl. Thrombosen"=round(`angenommenes Thrombose-Risiko`*Impfdosen),
         "Todesfaelle verhindert"=round(`Todesrate COVID-19`*`7-Tage-Fallrate`*Impfdosen),
         "Todesfaelle verhindert bei doppelter Inzidenz"=round(`Todesrate COVID-19`*`7-Tage-Fallrate`*2*Impfdosen))

resultdata %>%
  kbl() %>%
  kable_styling()
```